apiVersion: v1
kind: Service
metadata:
  name: mypythonimage-service
spec:
    ports:
    - port: 31001
      targetPort: python-port
      protocol: TCP
    selector:
      app: mypythonimage
    type: LoadBalancer  
